// require("classnames");
// require("dom-css");
// require("lodash");
// require("react");
// require("react-addons-update");
// require("react-addons-pure-render-mixin");
require("react-dom");
require("react-redux");
require("react-router");
require("semantic-ui-react");
require("redux-form");
// require("redux");
// require("redux-saga");
// require("redux-simple-router");
// require("redux-storage");
// require("moment/locale/pt-br");
// require("moment/min/moment.min");
// require("moment/src/locale/pt-br.js");
require("moment");