# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-21 18:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('limitacao', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4674)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Benfeitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4674)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContatoParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=100)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagemParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('imagem', models.ImageField(upload_to='parque/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_decreto', models.CharField(blank=True, max_length=256, null=True)),
                ('tipo', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.CharField(blank=True, max_length=250, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Limite oficial do parque.', null=True, srid=4674, verbose_name='Limite')),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Centro do parque.', null=True, srid=4674, verbose_name='Centro')),
                ('custo_entrada', models.CharField(blank=True, max_length=250, null=True)),
                ('periodo_abertura', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('regiao_administrativa', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parque',
            },
        ),
        migrations.CreateModel(
            name='TipoAtrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.FileField(upload_to='atrativo/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoBenfeitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.FileField(upload_to='estrutura/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoYoutube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('autor', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitanteParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parque',
            name='visitantes',
            field=models.ManyToManyField(related_name='visitante_parque', through='parque.VisitanteParque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagemparque',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque'),
        ),
        migrations.AddField(
            model_name='imagemparque',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contatoparque',
            name='parque',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque'),
        ),
        migrations.AddField(
            model_name='contatoparque',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benfeitoria',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque'),
        ),
        migrations.AddField(
            model_name='benfeitoria',
            name='tipo_benfeitoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.TipoBenfeitoria'),
        ),
        migrations.AddField(
            model_name='benfeitoria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atrativo',
            name='parque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Parque'),
        ),
        migrations.AddField(
            model_name='atrativo',
            name='tipo_atrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.TipoAtrativo'),
        ),
        migrations.AddField(
            model_name='atrativo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
