# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitanteparque',
            options={'verbose_name': 'Elemento Basico'},
        ),
        migrations.AddField(
            model_name='tipoatrativo',
            name='tipo_geom',
            field=models.CharField(choices=[('0', 'Ponto'), ('1', 'Linha'), ('2', 'Polígono')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='tipobenfeitoria',
            name='tipo_geom',
            field=models.CharField(choices=[('0', 'Ponto'), ('1', 'Linha'), ('2', 'Polígono')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='visitanteparque',
            name='oficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitanteparque',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
