# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-12-03 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0002_auto_20190729_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitanteparque',
            options={},
        ),
    ]
