# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-02 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parque', '0004_auto_20191209_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemAtrativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('imagem', models.ImageField(upload_to='atrativoimagens/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoAtrativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('autor', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atrativo',
            name='nome',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='videoatrativo',
            name='atrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Atrativo'),
        ),
        migrations.AddField(
            model_name='videoatrativo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagematrativos',
            name='atrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.Atrativo'),
        ),
        migrations.AddField(
            model_name='imagematrativos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
