# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-02 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0005_auto_20210702_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagemAtrativos',
            new_name='ImagemAtrativo',
        ),
    ]
