# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-16 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0007_atrativo_cor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagemAtrativo',
            new_name='ImagemAtrativoParque',
        ),
        migrations.RenameModel(
            old_name='VideoAtrativo',
            new_name='VideoAtrativoParque',
        ),
    ]
