# Generated by Django 5.2 on 2025-05-02 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0008_auto_20210716_1653'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parque',
            name='visitantes',
            field=models.ManyToManyField(related_name='visitante_parque', through='parque.VisitanteParque', through_fields=('parque', 'visitante'), to=settings.AUTH_USER_MODEL),
        ),
    ]
