# Generated by Django 5.2 on 2025-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0010_alter_atrativo_id_alter_benfeitoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atrativo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
