/**@
* #Crafty.import
* @sign public void Crafty.import(String url[, String scene])
* @param url - Path to the saved file
* @param scene - Name of the scene to load if saved multiple scenes
* @sign public void Crafty.import(Object sceneData)
* @param sceneData - Scene data generated from builder
* This method will load in scene data generated by the Crafty Builder.
*
* @example
* ~~~
* Crafty.import({
*	'0': {props: value},
*	'n': [
*		{c: "comp, list", image: ''}
*	]
* });
* ~~~
*/Crafty.import=function(e,t){if(typeof e=="string"){if(levelData)t?Crafty.import(levelData[t]):Crafty.import(levelData);else{var n;n=document.createElement("script");n.onload=function(){t?Crafty.import(levelData[t]):Crafty.import(levelData)};n.src=e}return}var r,i=0,s,o,u;if(e.n&&typeof e.n=="object")for(s=e.n.length;i<s;++i){o=e.n[i];u=Crafty.e(o.c);delete o.c;u.attr(o)}for(r in e){u=Crafty(r);u.attr(e[r])}};