# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-29 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=500)),
                ('texto', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Texto Home',
            },
        ),
        migrations.RenameModel(
            old_name='Texto',
            new_name='TextoHome',
        ),
        migrations.AlterModelOptions(
            name='textohome',
            options={'verbose_name': 'Texto Home'},
        ),
    ]
