# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-09-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='textohome',
            name='identificador',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
