# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-21 18:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilha', '0001_initial'),
        ('parque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('imagem', models.ImageField(upload_to='especie/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4674)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ocorrencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEspecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome_cientifico', models.CharField(max_length=200, verbose_name='Nome Científico')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Popular')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Link')),
                ('categoria', models.CharField(choices=[('ave', 'Ave'), ('arvore', 'Árvore '), ('fruto', 'Fruto'), ('mamifero', 'Mamífero'), ('peixe', 'Peixe'), ('desconhecido', 'Desconhecido')], default='des', max_length=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Espécie',
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especie.TipoEspecie'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='parque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parque.Parque'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trilha.Trilha'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagemespecie',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especie.TipoEspecie'),
        ),
        migrations.AddField(
            model_name='imagemespecie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
