# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-29 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemespecie',
            options={'verbose_name': 'Elemento Basico'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'verbose_name': 'Elemento Basico'},
        ),
    ]
