# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0002_auto_20190729_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoespecie',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor'),
        ),
    ]
