# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-12-03 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0003_tipoespecie_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemespecie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={},
        ),
    ]
