# Generated by Django 5.2 on 2025-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0004_auto_20191203_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemespecie',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoespecie',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
