# Generated by Django 5.2 on 2025-05-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0005_alter_imagemespecie_id_alter_ocorrencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoespecie',
            name='categoria',
            field=models.CharField(choices=[('ave', 'Ave'), ('arvore', 'Árvore '), ('fruto', 'Fruto'), ('mamifero', 'Mamífero'), ('peixe', 'Peixe'), ('desconhecido', 'Desconhecido')], default='des', max_length=12, verbose_name='Categoria'),
        ),
    ]
