# Generated by Django 5.2 on 2025-12-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0006_alter_tipoespecie_categoria'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoespecie',
            table='especie_tipoespecie',
        ),
    ]
