# # Teste para desenvolvimento - Rodar localmente
# FROM node:10 AS node

# WORKDIR /app

# COPY package.json package-lock.json* ./
# RUN npm install

# COPY . .

# EXPOSE 8686

# CMD ["npm", "start"]

FROM node:10

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 8080

CMD ["npm", "start"]