# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-21 18:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficial', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(help_text='Linha que define a Trilha', srid=4674, verbose_name='Traçado da Trilha')),
                ('geom3d', django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, help_text='Linha 3D que define a Trilha', null=True, srid=4674, verbose_name='Traçado 3D')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('regiao_administrativa', models.CharField(blank=True, max_length=250, null=True)),
                ('categoria', models.CharField(choices=[('0', 'Fácil'), ('1', 'Moderada'), ('2', 'Difícil'), ('3', 'Muito Difícil'), ('3', 'Para Especialistas'), ('-1', 'Desconhecido')], default='-1', max_length=2)),
                ('parque', models.ForeignKey(blank=True, help_text='Parque associado', null=True, on_delete=django.db.models.deletion.CASCADE, to='parque.Parque', verbose_name='Parque')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trilha',
            },
        ),
        migrations.CreateModel(
            name='Trilha_3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('geom3d', django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, help_text='Linha 3D que define a Trilha', null=True, srid=4674, verbose_name='Traçado 3D')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trilha',
            },
        ),
        migrations.CreateModel(
            name='VisitanteTrilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilha.Trilha')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_t', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trilha',
            name='visitantes',
            field=models.ManyToManyField(related_name='visitante_trilha', through='trilha.VisitanteTrilha', to=settings.AUTH_USER_MODEL),
        ),
    ]
