# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-29 15:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trilha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.FileField(upload_to='atividade/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='visitantetrilha',
            options={'verbose_name': 'Elemento Basico'},
        ),
        migrations.AddField(
            model_name='trilha',
            name='sinalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitantetrilha',
            name='oficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitantetrilha',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Linha que define a Trilha', null=True, srid=4674, verbose_name='Traçado da Trilha'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(to='trilha.TipoAtividade'),
        ),
    ]
