# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0002_auto_20190729_1509'),
        ('trilha', '0002_auto_20190729_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='parque',
        ),
        migrations.AddField(
            model_name='trilha',
            name='parque',
            field=models.ManyToManyField(help_text='Parque associado', to='parque.Parque', verbose_name='Parque'),
        ),
    ]
