# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0002_auto_20190729_1509'),
        ('trilha', '0003_auto_20190805_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='parque',
        ),
        migrations.AddField(
            model_name='trilha',
            name='parques',
            field=models.ManyToManyField(help_text='Parques associados', to='parque.Parque', verbose_name='Parques'),
        ),
    ]
