# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0004_auto_20190805_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(blank=True, null=True, to='trilha.TipoAtividade'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='parques',
            field=models.ManyToManyField(blank=True, help_text='Parques associados', null=True, to='parque.Parque', verbose_name='Parques'),
        ),
    ]
