# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-12-09 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0006_auto_20191203_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeVideo',
            new_name='VideoYoutubeTrilha',
        ),
    ]
