# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-03-16 19:07
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trilha', '0007_auto_20191209_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtrativoTrilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('limitacao', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4674)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAtrativoTrilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.FileField(upload_to='atrativo/')),
                ('tipo_geom', models.CharField(choices=[('0', 'Ponto'), ('1', 'Linha'), ('2', 'Polígono')], default='0', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atrativotrilha',
            name='tipo_atrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilha.TipoAtrativoTrilha'),
        ),
        migrations.AddField(
            model_name='atrativotrilha',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilha.Trilha'),
        ),
        migrations.AddField(
            model_name='atrativotrilha',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
