# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-07-02 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0009_auto_20210702_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagemAtrativosTrilha',
            new_name='ImagemAtrativoTrilha',
        ),
        migrations.RenameModel(
            old_name='VideoAtrativoTrilhas',
            new_name='VideoAtrativoTrilha',
        ),
        migrations.RemoveField(
            model_name='tipoatrativotrilha',
            name='user',
        ),
        migrations.AlterField(
            model_name='atrativotrilha',
            name='tipo_atrativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parque.TipoAtrativo'),
        ),
        migrations.DeleteModel(
            name='TipoAtrativoTrilha',
        ),
    ]
