# Generated by Django 5.2 on 2025-05-02 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0010_auto_20210702_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='visitantes',
            field=models.ManyToManyField(related_name='visitante_trilha', through='trilha.VisitanteTrilha', through_fields=('trilha', 'visitante'), to=settings.AUTH_USER_MODEL),
        ),
    ]
