# Generated by Django 5.2 on 2025-05-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parque', '0010_alter_atrativo_id_alter_benfeitoria_id_and_more'),
        ('trilha', '0012_alter_atrativotrilha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='trilha.tipoatividade'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='parques',
            field=models.ManyToManyField(blank=True, help_text='Parques associados', to='parque.parque', verbose_name='Parques'),
        ),
    ]
